# Generated by Django 3.2.5 on 2021-07-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('load_images', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageDetails',
            new_name='ImageDetail',
        ),
    ]
