# Generated by Django 3.2.5 on 2021-07-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_images', '0002_rename_imagedetails_imagedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedetail',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
