# Generated by Django 3.2.5 on 2021-07-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_images', '0003_alter_imagedetail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
