# Generated by Django 3.2.5 on 2021-07-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_images', '0004_alter_imagedetail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedetail',
            name='image',
            field=models.ImageField(upload_to='image_gallery/static/img'),
        ),
    ]
