# Generated by Django 3.2.5 on 2021-07-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_images', '0005_alter_imagedetail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedetail',
            name='image',
            field=models.URLField(),
        ),
    ]
